import useSWR from 'swr';
import NavBar from "../../comps/navbar";
import Head from 'next/head'
import Footer from "../../comps/footer";
import Router, { useRouter } from 'next/router';
import { URLS } from '../../constants/urls';
import { request } from '../../helpers/request';

export default function Article() {
  const router = useRouter()
  const { id: articleId } = router.query
  
  const { data: article, error } = useSWR(`/api/articles/${articleId}`, request);

  if (error) {
    return (
      <div className=" w-3/4 px-16 py-5 justify-center align-middle">
        <h1 className="text-4xl  content-center font-bold tracking-tight text-zinc-100">Failed to load</h1>
      </div>
    )
  }
  if (!article) {
    return (
      <div className=" w-3/4 px-16 py-5 justify-center align-middle">
        <h1 className="text-4xl  content-center font-bold tracking-tight text-zinc-100">Loading...</h1>
      </div>
    )
  }

  return (
    <div>
      <Head>
        <title>Article: {article.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <div className="px-16 w-11/12">
        <h1 className="text-4xl my-10 font-bold tracking-tight text-zinc-100">{article.title}</h1>
        <p>{article.content}</p>
      </div>
      <Footer />
    </div>
  );
}
