import useSWR from 'swr';
import NavBar from "../../comps/navbar";
import Head from 'next/head'
import Footer from "../../comps/footer";
import Router from 'next/router';
import { URLS } from '../../constants/urls';
import { request } from '../../helpers/request';
import { Key } from 'react';

export default function Page() {
  const { data, error } = useSWR('/api/articles', request);
  if (error) {
    return (
      <div className=" w-3/4 px-16 py-5 justify-center align-middle">
        <h1 className="text-4xl  content-center font-bold tracking-tight text-zinc-100">Failed to load</h1>
      </div>
    )
  }
  if (!data) {
    return (
      <div className="w-3/4 px-16 py-5 justify-center align-middle">
        <h1 className="text-4xl  content-center font-bold tracking-tight text-zinc-100">Loading...</h1>
      </div>
    )
  }
  return (
    <div>
      <Head>
        <title>Articles</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <div className="px-16 w-11/12">
        <h1 className="text-4xl my-10 font-bold tracking-tight text-zinc-100">Writing on software design, company building, and the aerospace industry.</h1>
        <p className="text-base text-zinc-400 mb-10">All of my long-form thoughts on programming, leadership, product design, and more, collected in chronological order.</p>
        {data.articles.map((article: { id: Key; date: string ; title: string ; content: string ; }) => (
          <div key={article.id}>
            <div className="grid grid-cols-3">
              <div className="col-span-1 border-l-[1px] p-4 border-zinc-600">
                <time className="flex justify-start text-sm text-zinc-500 pl-3.5">{article.date}</time>
              </div>
              <div className="col-span-2 rounded-xl transition mb-5 hover:bg-zinc-800" onClick={() => { Router.push(`${URLS.ARTICLES}/${article.id}`) }}>
                <h2 className="p-4 text-base font-semibold text-zinc-100">{article.title}</h2>
                <p className=" px-4 text-sm text-zinc-400">{article.content}</p>
                <h2 className="py-4 inherit text-sm font-medium pl-4 text-teal-500">Read Article {">"}</h2>
              </div>
            </div>
          </div>
        ))}
      </div>
      <Footer />
    </div>
  );
}
