import NavBar from "../comps/navbar";
import Head from 'next/head'
import data from './data.json'
import path from 'path'
import Footer from "../comps/footer";
import Link from "next/link";
import { Button } from "@mui/material";

const Page = () => {
  return (
    <div>
      <Head>
        <title>Articles</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://spotlight.tailwindui.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Favatar.51a13c67.jpg&w=128&q=75" />
      </Head>
      <NavBar />
      <div className="px-16 pb-16">
        <h1 className='text-4xl my-10 font-bold tracking-tight text-zinc-100 '>Writing on software design, company building, and the aerospace industry.</h1>
        <p className='text-base text-zinc-400 mb-10'>All of my long-form thoughts on programming, leadership, product design, and more, collected in chronological order.</p>
        {data.articles.map(article => (
          <div className=''
            key={article.id}>
            <time className='relative border-l-2 border-zinc-500 mb-3 flex items-center text-sm text-zinc-500 pl-3.5'>{article.date}</time>
            <h2 className='text-base font-semibold text-zinc-100'>{article.title}</h2>
            <p className='text-sm text-zinc-400'>{article.content}</p>
            <Button className='mb-6 text-teal-400' onClick={() => { console.log(article.id) }}>Read More</Button>
          </div>))}
      </div>
      <Footer />
    </div>
  )
}
export default Page;
