import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Navbar from '../comps/navbar'
import Footer from '../comps/footer'
import TwitterIcon from '@mui/icons-material/Twitter';
import InstagramIcon from '@mui/icons-material/Instagram';
import GitHubIcon from '@mui/icons-material/GitHub';
import LinkedInIcon from '@mui/icons-material/LinkedIn';
import Link from 'next/link';
import data from './data.json';


export default function Home(props) {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://spotlight.tailwindui.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Favatar.51a13c67.jpg&w=128&q=75" />
      </Head>
      <main>
        <Navbar />
        <div className='w-3/4 px-16 py-5'>
          <h1 className='text-4xl font-bold tracking-tight text-zinc-100 '>Software designer, founder, and amateur astronaut.</h1>
          <p className='mt-6 text-base text-zinc-400'>I’m Spencer, a software designer and entrepreneur based in New York City. I’m the founder and CEO of Planetaria, where we develop technologies that empower regular people to explore space on their own terms.</p>
        </div>
        <div className='px-16 pb-16'>
          <Link href='https://www.twitter.com/'><TwitterIcon className='mr-4 fill-zinc-400' /></Link>
          <Link href='https://www.instagram.com/'><InstagramIcon className='mr-4 fill-zinc-400' /></Link>
          <Link href='https://www.github.com/'><GitHubIcon className='mr-4 fill-zinc-400' /></Link>
          <Link href='https://www.linkedin.com'><LinkedInIcon className='mr-4 fill-zinc-400' /></Link>
        </div>
        <div className='-my-4 abso flex justify-center gap-5 py-4 pb-16'>
          <img className='relative aspect-[9/10] w-72 flex-none overflow-hidden rounded-xl -rotate-2' src='https://spotlight.tailwindui.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fimage-1.c5d2141c.jpg&w=384&q=75'></img>
          <img className='relative aspect-[9/10] w-72 flex-none overflow-hidden rounded-xl rotate-2' src='https://spotlight.tailwindui.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fimage-2.3c6c01cf.jpg&w=384&q=75'></img>
          <img className='relative aspect-[9/10] w-72 flex-none overflow-hidden rounded-xl -rotate-2' src='https://spotlight.tailwindui.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fimage-1.c5d2141c.jpg&w=640&q=75'></img>
          <img className='relative aspect-[9/10] w-72 flex-none overflow-hidden rounded-xl rotate-2' src='https://spotlight.tailwindui.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fimage-4.5c6d0ed6.jpg&w=384&q=75'></img>
          <img className='relative aspect-[9/10] w-72 flex-none overflow-hidden rounded-xl -rotate-2' src='https://spotlight.tailwindui.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fimage-5.6c6f2784.jpg&w=384&q=75'></img>
        </div>
        <div className='px-16 pb-16'>
          {data.articles.map(article => (
            <div key={article.id}>
              <time className='border-l-2 border-zinc-500 mb-3 flex items-center text-sm text-zinc-500 pl-3.5'>{article.date}</time>
              <h2 className='text-base font-semibold tracking-tight text-zinc-100'>{article.title}</h2>
              <p className=' mt-2 pb-10 text-sm text-zinc-400'>{article.content}</p>
            </div>
          ))}
        </div>
        <Footer />
      </main>
    </>
  )
}